WebManagement/Controllers/HRController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Todo.Data.Sales;
using Todo.Domain.Sales;
using Todo.Domain.ViewModels;
using static Slapper.AutoMapper;

namespace WebManagement.Controllers
{
    public class HRController : Controller
    {
        enum Role
        {
            ADMIN = 1,
            STAFF = 2,
            SHOP = 3,
            CUSTOMER = 4,
        }
        enum Active
        {
            DISABLE = 0,
            ACTIVE = 1,
        }
        IAuth_Repository _authRepository;
        IHRManagement_Repository _hrRepository;
        public HRController(IHRManagement_Repository hrRepository, IAuth_Repository auth_Repository) 
        {
            _hrRepository = hrRepository;
            _authRepository = auth_Repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User emp)
        {
            var loginResult = await _authRepository.CheckLogin(emp);

            if (loginResult.success)
            {
                HttpContext.Session.SetInt32("Role", emp.role_id);
                return View("Customer");
            }

            return View("Index");
        }


        public IActionResult Customer(int id)
        {
            if (id > 0)
            {
                ViewBag.Id = id;
            }
            return View();
        }

        public IActionResult Staff()
        {
            return View();
        }

        public async Task<ActionResult> Customers_Read([DataSourceRequest] DataSourceRequest dsrequest, string id)
        {
            var customers = await _hrRepository.GetAllCustomer();

            // Check If Not Success -> return Error
            if (!customers.success)
            {
                return Json(new DataSourceResult
                {
                    Errors = new[] { customers.message },
                });
            }

            IEnumerable<UserViewModel> result = customers.data;

            if (!string.IsNullOrEmpty(id))
            {
                result = result.Where(p => p.user_id.Equals( int.Parse(id) ));
            }

            return new JsonResult(result.ToDataSourceResult(dsrequest));
        }

        public async Task<ActionResult> Staffs_Read([DataSourceRequest] DataSourceRequest dsrequest)
        {

            var employees = await _hrRepository.GetByRole((int)Role.STAFF);

            // Check If Not Success -> return Error
            if (!employees.success)
            {
                return Json(new DataSourceResult
                {
                    Errors = new[] { employees.message },
                });
            }

            return new JsonResult(employees.data.ToDataSourceResult(dsrequest));
        }

    }
}

WebManagement/Controllers/PackageController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Todo.Data.Sales;
using OfficeOpenXml;
using Todo.Data.SalesDto;
using System.Text;
using Todo.Domain.ViewModels;
using Todo.Data.shop.Service;

namespace WebManagement.Controllers
{
    public class PackageController : Controller
    {
        enum Role
        {
            ADMIN = 1,
            STAFF = 2,
            SHOP = 3,
            CUSTOMER = 4,
        }

        IPackageManagement_Repository _packageRepository;
        IPackageManagement_Service _packageService;
        public PackageController(IPackageManagement_Repository packageRepository, IPackageManagement_Service packageService)
        {
            _packageRepository = packageRepository;
            _packageService = packageService;
        }
        public IActionResult Order()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            //ViewData["Aggr"] = (await _packageRepository.GetAggregatePackage()).data;
            return View();
        }

        /// <summary>
        /// Dùng cho trang Index gọi đến để lấy dữ liệu từ Service
        /// </summary>
        /// <param name="dsrequest"></param>
        /// <param name="customerName"></param>
        /// <param name="cod"></param>
        /// <returns></returns>
        public async Task<ActionResult> TransportWithOrder_Read([DataSourceRequest] DataSourceRequest dsrequest, string customerName, string cod)
        {
            return Json( (await _packageService.GetAllPackage(dsrequest, customerName, cod)).data);
        }


        public async Task<ActionResult> OrdersByUserId_Read(int id, [DataSourceRequest] DataSourceRequest dsrequest)
        {

            var orders = await _packageRepository.GetOrderByUserId(id);

            // Check If Not Success -> return Error
            if (!orders.success)
            {
                return Json(new DataSourceResult
                {
                    Errors = new[] { orders.message },
                });
            }

            return new JsonResult(orders.data.ToDataSourceResult(dsrequest));
        }

        [HttpPost]
        public async Task<IActionResult> Upload()
        {
            var file = Request.Form.Files[0];

            if (file != null && file.Length > 0)
            {
                using (var stream = new MemoryStream())
                {
                    await file.CopyToAsync(stream);
                    using (var package = new ExcelPackage(stream))
                    {
                        var worksheet = package.Workbook.Worksheets.First();
                        var rowCount = worksheet.Dimension.Rows;

                        for (int row = 2; row <= rowCount; row++)
                        {
                            var userIdAndName = worksheet.Cells[row, 3].Text;
                            string[] userParts = new string[2];

                            if (!string.IsNullOrEmpty(userIdAndName) && userIdAndName.Contains(' '))
                            {
                                userParts = userIdAndName.Split([' '], 2);
                            }
                            else
                            {
                                userParts[1] = "No name";
                            }
                            var user = new UserDto
                            {
                                user_code = userIdAndName,
                                first_name = userParts[1],
                                phone_number = worksheet.Cells[row, 15].Text,
                                role_id = (int)Role.CUSTOMER,
                            };

                            var addressIdAndWard = worksheet.Cells[row, 26].Text;
                            string[] addressParts = new string[2];
                            addressParts = addressIdAndWard.Split(['-'], 2);

                            var address = new AddressDto
                            {
                                address_code = addressParts[1],
                                province = worksheet.Cells[row, 24].Text,
                                city = worksheet.Cells[row, 25].Text,
                                ward = addressParts[0],
                                street = worksheet.Cells[row, 27].Text,
                                phone_number = worksheet.Cells[row, 15].Text,
                                postal_code = worksheet.Cells[row, 20].Text,
                            };

                            var order = new OrderDto
                            {
                                order_code = worksheet.Cells[row, 14].Text,
                                order_name = worksheet.Cells[row, 4].Text,
                                amount = float.TryParse(worksheet.Cells[row, 7].Text, out float Amount) ? Amount : 0,
                                customer_first_name = userParts[1],
                                customer_phone_number = worksheet.Cells[row, 15].Text,
                                customer_province = worksheet.Cells[row, 24].Text,
                                customer_city = worksheet.Cells[row, 25].Text,
                                customer_ward = addressParts[0],
                                customer_street = worksheet.Cells[row, 27].Text,
                                shop_first_name = worksheet.Cells[row, 30].Text,
                                shop_phone_number = worksheet.Cells[row, 31].Text,
                                shop_street = worksheet.Cells[row, 33].Text,
                                postal_code = worksheet.Cells[row, 20].Text,
                                payment_method = worksheet.Cells[row, 19].Text,
                                creation_time = DateTime.TryParse(worksheet.Cells[row, 28].Text, out DateTime CreationTime) ? CreationTime : new DateTime(),
                                shop_id = 1,
                            };

                            var transport = new ShippingDto
                            {
                                ship_code = worksheet.Cells[row, 1].Text,
                                ship_name = worksheet.Cells[row, 4].Text,
                                shipp_charges = float.TryParse(worksheet.Cells[row, 6].Text, out float ShippingCharges) ? ShippingCharges : 0,
                                cod = float.TryParse(worksheet.Cells[row, 7].Text, out float Cod) ? Cod : 0,
                                number_of_print = int.TryParse(worksheet.Cells[row, 10].Text, out int NumberOfPrint) ? NumberOfPrint : 0,
                                status = worksheet.Cells[row, 11].Text,
                                problem_type = worksheet.Cells[row, 13].Text,
                                weight = float.TryParse(worksheet.Cells[row, 17].Text, out float Weight) ? Weight : 0,
                                other_fee = float.TryParse(worksheet.Cells[row, 18].Text, out float OtherFee) ? OtherFee : 0,
                                hs_code = worksheet.Cells[row, 21].Text,
                                delivery_service = worksheet.Cells[row, 22].Text,
                                description = worksheet.Cells[row, 29].Text,
                            };

                            await _packageRepository.UploadExcel(user, address, order, transport);
                        }
                    }
                }

                return RedirectToAction("Index");
            }

            return BadRequest("Invalid file");
        }

        private static string GenerateRandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            StringBuilder result = new StringBuilder(length);
            Random random = new Random();

            for (int i = 0; i < length; i++)
            {
                result.Append(chars[random.Next(chars.Length)]);
            }

            return result.ToString();
        }
    }
}

WebManagement/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebManagement</title>
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/js/bootstrap.min.js" /> *@
    <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    @* Bootstrap & jQuery: *@
    <link href="~/css/custom.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/themes/8.2.1/default/default-main.css" />
    
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>

    @* Gritter Notify: *@
    <link href="https://www.jqueryscript.net/demo/Classic-Growl-like-Notification-Plugin-For-jQuery-Gritter/css/jquery.gritter.css" rel="stylesheet" />
    <script src="https://www.jqueryscript.net/demo/Classic-Growl-like-Notification-Plugin-For-jQuery-Gritter/js/jquery.gritter.js"></script>

    @* Add the Kendo UI scripts: *@
    <script src="https://unpkg.com/jszip/dist/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2024.3.806/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2024.3.806/js/kendo.aspnetmvc.min.js"></script>

    @* License: *@
    <script src="~/kendo-ui-license.js"></script>
    <style>
        *{
            font-family: "Be Vietnam Pro", sans-serif;
            font-weight: 300;
            font-style: normal;
            color: black;
            font-size: 11px;
            font-weight: 300 !important;
        }

        body{
            caret-color: transparent;
        }

        input{
            caret-color: black;
        }

        #k-license-banner{
            display: none !important;
        }

        .text-ellipsis, .k-grid-footer td {
            overflow: hidden !important;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }

        a {
            text-decoration: none;
        }

        #gritter-notice-wrapper {
            position: fixed;
            top: 40px;
            right: 50%;
            transform: translateX(50%);
            width: 500px;
            z-index: 9999;
        }

            #gritter-notice-wrapper.top-left {
                left: 20px;
                right: auto;
            }

            #gritter-notice-wrapper.bottom-right {
                top: auto;
                left: auto;
                bottom: 20px;
                right: 20px;
            }

            #gritter-notice-wrapper.bottom-left {
                top: auto;
                right: auto;
                bottom: 20px;
                left: 20px;
            }

        .gritter-item-wrapper {
            position: relative;
            margin: 0 0 10px 0;
        }

        .gritter-item {
            display: block;
            color: #eee;
            padding: 2px 11px 8px 11px;
            font-size: 11px;
            font-family: verdana;
        }

        .hover .gritter-item {
            background-position: right -40px;
        }

        .gritter-item p {
            padding: 0;
            margin: 0;
            word-wrap: break-word;
        }

        .gritter-title {
            font-size: 14px;
            font-weight: bold;
            padding: 0 0 7px 0;
            display: block;
        }

        .gritter-close {
            left: unset;
            right: 0px;
        }

        .gritter-with-image,
        .gritter-without-image {
            padding: 0;
        }
        /* for the light (white) version of the gritter notice */
        .gritter-light .gritter-item,
        .gritter-light .gritter-bottom,
        .gritter-light .gritter-top,
        .gritter-light .gritter-close {
            color: #222;
        }

        .gritter-light .gritter-title {
            text-shadow: none;
        }

        #gritter-notice-wrapper .gritter-item-wrapper {
            position: relative;
            margin: 0 0 10px 0;
        }

            #gritter-notice-wrapper .gritter-item-wrapper .gritter-item {
                display: block;
                background: #657791;
                border: 1px solid #455264;
                color: #ffffff;
                padding: 10px 11px;
                font-size: 12px;
                border-radius: 3px;
                transition: all;
                transition: all all ease-out;
                transition-duration: 0.4s;
            }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item:hover {
                    background: #72849e;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item p {
                    padding: 0;
                    margin: 0;
                    word-wrap: break-word;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-close i {
                    font-size: 16px;
                    color: #ffffff;
                    transition: background;
                    transition: all background ease-out;
                    transition-duration: 0.4s;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-close:hover i {
                    color: #f7f7f7;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-image {
                    width: 48px;
                    height: 48px;
                    float: left;
                    border-radius: 3px;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-icon {
                    margin-top: 0;
                    margin-right: 15px;
                    float: left;
                    font-size: 32px;
                    padding-bottom: 10px;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-without-image {
                    padding: 0;
                }

                #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-title {
                    font-size: 14px;
                    font-weight: bold;
                    padding: 0;
                    display: block;
                }

            #gritter-notice-wrapper .gritter-item-wrapper.success-notice .gritter-item {
                color: #0a776c;
                background: #b2ede8;
                border: 1px solid #63c8be;
            }

                #gritter-notice-wrapper .gritter-item-wrapper.success-notice .gritter-item:hover {
                    background: #c7f2ee;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.success-notice .gritter-item .gritter-close i {
                    color: #0a776c;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.success-notice .gritter-item .gritter-close:hover i {
                    color: #09695f;
                }

            #gritter-notice-wrapper .gritter-item-wrapper.info-notice .gritter-item {
                color: #2a6891;
                background: #cfebff;
                border: 1px solid #94bedb;
            }

                #gritter-notice-wrapper .gritter-item-wrapper.info-notice .gritter-item:hover {
                    background: #e9f6ff;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.info-notice .gritter-item .gritter-close i {
                    color: #2a6891;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.info-notice .gritter-item .gritter-close:hover i {
                    color: #275f85;
                }

            #gritter-notice-wrapper .gritter-item-wrapper.error-notice .gritter-item {
                color: #933230;
                background: #fddede;
                border: 1px solid #cb7c7a;
            }

                #gritter-notice-wrapper .gritter-item-wrapper.error-notice .gritter-item:hover {
                    background: #fef6f6;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.error-notice .gritter-item .gritter-close i {
                    color: #933230;
                }

                #gritter-notice-wrapper .gritter-item-wrapper.error-notice .gritter-item .gritter-close:hover i {
                    color: #872e2c;
                }

        .gritter-top, .gritter-bottom {
            background: #cfebff;
            opacity: .5;
            height: 5px;
            margin: 0;
        }
    </style>
</head>
<body>

    @{
         @*
        var role = HttpContextAccessor.HttpContext.Session.GetInt32("Role");
        if (role != null)
        {
            await Html.RenderPartialAsync("_NavbarPartial");
        }
        *@
        await Html.RenderPartialAsync("_NavbarPartial");
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

WebManagement/Views/Shared/_NavbarPartial.cshtml
@{
}

<style>
    .nav-bar {
        margin-top: 15px;
        width 100%;
        display: flex;
        justify-content: space-around;
        margin-bottom: 50px;
    }

    .nav-bar div {
        display: flex;
        align-items: baseline;
    }

    .nav-bar div span {
        font-size: 20px;
        margin-right: 15px;
    }

    .nav-bar div ul li {
        list-style-type: none;
        display: inline;
        margin-right: 10px;
    }
</style>

<div class="nav-bar">
    <div>
        <span> HR </span>
        <ul>
            <li>
                <a href="#">Admin</a>
            </li>
            <li>
                <a asp-action="Staff" asp-controller="HR">Staff</a>
            </li>
            <li>
                <a asp-action="Shop" asp-controller="HR">Shop</a>
            </li>
            <li>
                <a asp-action="Customer" asp-controller="HR">Customer</a>
            </li>
        </ul>
    </div>

    <div>
        <span> Package </span>
        <ul>
            <li>
                <a asp-action="Index" asp-controller="Package">Shipping</a>
            </li>
            <li>
                <a asp-action="Order" asp-controller="Package">Order</a>
            </li>
        </ul>
    </div>
</div>